### ISSUE TITLE
TypeError: Additional kwargs key is_blocked already exists

### ISSUE THREAD

**Issue by duob-ai** [langchain-ai/langchain-google#222]
This is probably related to this issue [here](https://github.com/langchain-ai/langchain-google/issues/177). 

Certain prompts in a simple RAG chain seem to cause a TypeError. Same prompts previously caused the IndexError mentioned in the above issue. No problems with other LLM providers like Azure.

**Full log from Langsmith**

TypeError("Additional kwargs key is_blocked already exists in left dict and value has unsupported type <class 'bool'>.")Traceback (most recent call last):

  File "/usr/local/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 1980, in _atransform_stream_with_config
    chunk: Output = await asyncio.create_task(  # type: ignore[call-arg]
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/langchain_core/tracers/log_stream.py", line 237, in tap_output_aiter
    async for chunk in output:

  File "/usr/local/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 2853, in _atransform
    async for output in final_pipeline:

  File "/usr/local/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 4748, in atransform
    async for item in self.bound.atransform(

  File "/usr/local/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 2883, in atransform
    async for chunk in self._atransform_stream_with_config(

  File "/usr/local/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 1980, in _atransform_stream_with_config
    chunk: Output = await asyncio.create_task(  # type: ignore[call-arg]
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/langchain_core/tracers/log_stream.py", line 237, in tap_output_aiter
    async for chunk in output:

  File "/usr/local/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 2853, in _atransform
    async for output in final_pipeline:

  File "/usr/local/lib/python3.11/site-packages/langchain_core/output_parsers/transform.py", line 60, in atransform
    async for chunk in self._atransform_stream_with_config(

  File "/usr/local/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 1980, in _atransform_stream_with_config
    chunk: Output = await asyncio.create_task(  # type: ignore[call-arg]
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/langchain_core/tracers/log_stream.py", line 237, in tap_output_aiter
    async for chunk in output:

  File "/usr/local/lib/python3.11/site-packages/langchain_core/output_parsers/transform.py", line 38, in _atransform
    async for chunk in input:

  File "/usr/local/lib/python3.11/site-packages/langchain_core/utils/aiter.py", line 97, in tee_peer
    item = await iterator.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 1334, in atransform
    async for output in self.astream(final, config, **kwargs):

  File "/usr/local/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 319, in astream
    raise e

  File "/usr/local/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 312, in astream
    generation += chunk

  File "/usr/local/lib/python3.11/site-packages/langchain_core/outputs/chat_generation.py", line 74, in __add__
    generation_info = merge_dicts(
                      ^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/langchain_core/utils/_merge.py", line 40, in merge_dicts
    raise TypeError(

TypeError: Additional kwargs key is_blocked already exists in left dict and value has unsupported type <class 'bool'>.

**Comment by lkuligin** [comment]
could you share a reproducible snippet, please?

**Comment by lkuligin** [comment]
I assume I have a fix, but it would be great if you could provide a reproducible example for a test case.
