### ISSUE TITLE
Adding option to use google credentials for _BaseGoogleGenerativeAI construction

### ISSUE THREAD

**Issue by jackklika** [langchain-ai/langchain-google#29]
Hi all, I have been using GoogleGenerativeAI in my code. However, in my environment I am using google credentials instead of an api key and the `GoogleGenerativeAI` model validation does not allow me to not specify an api key. I would be interested in contributing this feature but would like some guidance.

My personal workaround has been to override the root validator (mostly copy-paste) as follows:

```
import google.generativeai as genai
from langchain_google_genai import ChatGoogleGenerativeAI
from overrides import overrides
from pydantic.v1 import root_validator

from myapp.clients.google_client import get_creds


# overriding so we can use credentials to build instead of api key
class MyGoogleGenerativeAI(ChatGoogleGenerativeAI):
    @root_validator()
    def validate_environment(cls, values: dict) -> dict:
        #google_api_key = get_from_dict_or_env(
        #    values, "google_api_key", "GOOGLE_API_KEY"
        #)
        #if isinstance(google_api_key, SecretStr):
        #    google_api_key = google_api_key.get_secret_value()

        genai.configure(
            credentials=get_creds(), # <<< type google.auth.credentials.Credentials
            # api_key=google_api_key,
            transport=values.get("transport"),
            client_options=values.get("client_options"),
        )
        if values.get("temperature") is not None and not 0 <= values["temperature"] <= 1:
            raise ValueError("temperature must be in the range [0.0, 1.0]")

        if values.get("top_p") is not None and not 0 <= values["top_p"] <= 1:
            raise ValueError("top_p must be in the range [0.0, 1.0]")

        if values.get("top_k") is not None and values["top_k"] <= 0:
            raise ValueError("top_k must be positive")
        model = values["model"]
        values["client"] = genai.GenerativeModel(model_name=model)
        return values


llm = MyGoogleGenerativeAI(model="gemini-pro")

result = llm.invoke("Write a ballad about LangChain")
print(result.content)
```
My plan to contribute this feature was as follows:
- Add `credentials: Optional[Credentials]` to the `_BaseGoogleGenerativeAI` class
- In `ChatGoogleGenerativeAI` and `GoogleGenerativeAI` root validator, check if `credentials` attribute exists and prioritize using it for `genai.configure()` over the google_api_key logic

However, in my testing the `Credentials` object is not schema-able in pydantic:
```
from google.auth import credentials as ga_credentials
from pydantic import BaseModel
class A(BaseModel):
    creds: ga_credentials.Credentials
    
Traceback (most recent call last):
  File "/Users/aperson/Library/Caches/pypoetry/virtualenvs/myapp-YeMax3Mq-py3.11/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-6-d64b82d4a250>", line 1, in <module>
    class A(BaseModel):
  File "/Users/aperson/Library/Caches/pypoetry/virtualenvs/myapp-YeMax3Mq-py3.11/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py", line 183, in __new__
    complete_model_class(
  File "/Users/aperson/Library/Caches/pypoetry/virtualenvs/myapp-YeMax3Mq-py3.11/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py", line 517, in complete_model_class
    schema = cls.__get_pydantic_core_schema__(cls, handler)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  [...]
  File "/Users/aperson/Library/Caches/pypoetry/virtualenvs/myapp-YeMax3Mq-py3.11/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 851, in match_type
    return self._unknown_type_schema(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aperson/Library/Caches/pypoetry/virtualenvs/myapp-YeMax3Mq-py3.11/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 397, in _unknown_type_schema
    raise PydanticSchemaGenerationError(
pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class 'google.auth.credentials.Credentials'>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.
If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion.
For further information visit https://errors.pydantic.dev/2.6/u/schema-for-unknown-type                                                           
```

Does anyone have advice on how to implement this so we can instantiate `_BaseGoogleGenerativeAI` using a `google.auth.credentials.Credentials` credentials object instead of an api key?

**Comment by lkuligin** [comment]
you can take a look how it's done here:
https://github.com/langchain-ai/langchain-google/blob/87337a1550fc307eb168fa9f6c8328eae177fcf8/libs/vertexai/langchain_google_vertexai/llms.py#L151

**Comment by lkuligin** [comment]
@jackklika are you interested on implementing this one, or should I ask anybody else?

**Comment by jackklika** [comment]
@lkuligin I am interested but am having some trouble building the package and integrating it into my workflow. I have also been busy lately but should have more time soon.

**Comment by jackklika** [comment]
@lkuligin I have made a PR that is working for my purposes at #78 -- I'm not sure why integration tests are failing due to `E   ModuleNotFoundError: No module named 'google.cloud.aiplatform'` but it is working for me.
