### ISSUE TITLE
Additional kwargs key candidates_token_count already exists in left dict and value has unsupported type <class 'int'>.

### ISSUE THREAD

**Issue by hanfi** [langchain-ai/langchain-google#383]
hi my gemini-pro-vision-1.5 integration stopped working. with this error :

`Additional kwargs key candidates_token_count already exists in left dict and value has unsupported type <class 'int'>.`

he is how i'm creating it 
```
llm = ChatVertexAI( 
            model_name="gemini-1.5-pro-001", 
            convert_system_message_to_human=True,
            max_output_tokens="2048",  
            temperature=temperature,
            top_p=top_p,
            streaming=True,
            location=location_vertexai, 
            project_id=config.project_id,
            max_retries=1,
            verbose=True,
            callbacks=[StreamingStdOutCallbackHandler()],
        )
runnable = prompt_template | llm | StrOutputParser()
runnable.invoke({"question": content})
```
(i have the same issue with astream method.)

so the llm starts streaming the response then suddenly i get : 
`Additional kwargs key candidates_token_count already exists in left dict and value has unsupported type <class 'int'>.`

are you experiencing the same problem ??

**Comment by ccurme** [comment]
Hi @hanfi, thanks for this.

Could you please provide a snippet that reproduces the issue in isolation? I am having trouble reproducing it.

Here is a minimal snippet I came up with based on what you provided:
```python
from langchain_core.callbacks import StreamingStdOutCallbackHandler
from langchain_core.output_parsers import StrOutputParser
from langchain_core.prompts import ChatPromptTemplate
from langchain_google_vertexai import ChatVertexAI


temperature = 0
top_p = 1

llm = ChatVertexAI( 
    model_name="gemini-1.5-pro-001", 
    convert_system_message_to_human=True,
    max_output_tokens="2048",  
    temperature=temperature,
    top_p=top_p,
    streaming=True,
    # location=location_vertexai, 
    # project_id=config.project_id,
    max_retries=1,
    verbose=True,
    callbacks=[StreamingStdOutCallbackHandler()],
)

prompt_template = ChatPromptTemplate.from_messages(
    [
        (
            "human",
            "Please answer this question in 10 words or less: {question}"
        )
    ]
)


content = "what color is the sky"

runnable = prompt_template | llm | StrOutputParser()
runnable.invoke({"question": content})
```
This runs fine on
```
langchain-core==0.2.21
langchain-google-vertexai==1.0.6
```
Could you please help modify the example so that it reproduces your error?

Thanks.

**Comment by artdent** [comment]
I ran into this error specifically with multimodal inputs. The following snippet reproduces the error for me:

```
import base64

from langchain_core.messages import HumanMessage, SystemMessage
from langchain_core.callbacks import StreamingStdOutCallbackHandler
from langchain_core.output_parsers import StrOutputParser
from langchain_google_vertexai import ChatVertexAI


llm = ChatVertexAI(
    model_name="gemini-1.5-pro-001",
    convert_system_message_to_human=True,
    max_output_tokens="2048",
    temperature=0,
    top_p=1,
    streaming=True,
    max_retries=1,
    verbose=True,
    callbacks=[StreamingStdOutCallbackHandler()],
)


runnable = llm | StrOutputParser()
with open("pondering-my-orb.jpeg", "rb") as f:
    image_data = f.read()
    image_content = base64.b64encode(image_data).decode("utf-8")
runnable.invoke(
    [
        SystemMessage(content="Answer in 10 words or less."),
        HumanMessage(
            content=[
                {"type": "text", "text": "describe this image"},
                {"type": "image_url", "image_url": {"url": f"data:image/jpeg;base64,{image_content}"}},
            ]
        ),
    ]
)
```

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/jacob.lee/tempus/agent-service/scripts/gemini_repro.py", line 45, in <module>
    runnable.invoke(
  File "/Users/jacob.lee/Library/Caches/pypoetry/virtualenvs/agent-host-service--MyeOnt5-py3.11/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 2873, in invoke
    input = step.invoke(input, config, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jacob.lee/Library/Caches/pypoetry/virtualenvs/agent-host-service--MyeOnt5-py3.11/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 270, in invoke
    self.generate_prompt(
  File "/Users/jacob.lee/Library/Caches/pypoetry/virtualenvs/agent-host-service--MyeOnt5-py3.11/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 703, in generate_prompt
    return self.generate(prompt_messages, stop=stop, callbacks=callbacks, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jacob.lee/Library/Caches/pypoetry/virtualenvs/agent-host-service--MyeOnt5-py3.11/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 560, in generate
    raise e
  File "/Users/jacob.lee/Library/Caches/pypoetry/virtualenvs/agent-host-service--MyeOnt5-py3.11/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 550, in generate
    self._generate_with_cache(
  File "/Users/jacob.lee/Library/Caches/pypoetry/virtualenvs/agent-host-service--MyeOnt5-py3.11/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 775, in _generate_with_cache
    result = self._generate(
             ^^^^^^^^^^^^^^^
  File "/Users/jacob.lee/Library/Caches/pypoetry/virtualenvs/agent-host-service--MyeOnt5-py3.11/lib/python3.11/site-packages/langchain_google_vertexai/chat_models.py", line 1131, in _generate
    return generate_from_stream(stream_iter)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jacob.lee/Library/Caches/pypoetry/virtualenvs/agent-host-service--MyeOnt5-py3.11/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 104, in generate_from_stream
    generation += list(stream)
  File "/Users/jacob.lee/Library/Caches/pypoetry/virtualenvs/agent-host-service--MyeOnt5-py3.11/lib/python3.11/site-packages/langchain_core/outputs/chat_generation.py", line 106, in __add__
    generation_info = merge_dicts(
                      ^^^^^^^^^^^^
  File "/Users/jacob.lee/Library/Caches/pypoetry/virtualenvs/agent-host-service--MyeOnt5-py3.11/lib/python3.11/site-packages/langchain_core/utils/_merge.py", line 46, in merge_dicts
    merged[right_k] = merge_dicts(merged[right_k], right_v)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jacob.lee/Library/Caches/pypoetry/virtualenvs/agent-host-service--MyeOnt5-py3.11/lib/python3.11/site-packages/langchain_core/utils/_merge.py", line 52, in merge_dicts
    raise TypeError(
TypeError: Additional kwargs key candidates_token_count already exists in left dict and value has unsupported type <class 'int'>.
```

```
langchain-core = "^0.2.23"
langchain-google-vertexai = "^1.0.7"
```

**Comment by artdent** [comment]
I've verified that the issue goes away after downgrading to `1.0.5`. It looks like #292 introduced the error in attempting to allow merging `usage_metadata` during streaming.
