### ISSUE TITLE
VertexAIEmbeddings model failing to initialize after v2.0.0 update

### ISSUE THREAD

**Issue by hutariq** [langchain-ai/langchain-google#497]
Before the update model initialization was working fine with the following params:

```python
VertexAIEmbeddings(
    model_name=self._model_name,
    project=self._project_id,
    location=self._location
)
```

But after the update I started getting the following error:

```shell
Traceback (most recent call last):
  File "test.py", line 29, in <module>
    model = VertexAIEmbeddings(
            ^^^^^^^^^^^^^^^^^^^
  File "venv/lib/python3.11/site-packages/langchain_google_vertexai/embeddings.py", line 145, in __init__
    super().__init__(
  File ".venv/lib/python3.11/site-packages/pydantic/main.py", line 209, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/pydantic/_internal/_mock_val_ser.py", line 99, in __getattr__
    raise PydanticUserError(self._error_message, code=self._code)
pydantic.errors.PydanticUserError: `VertexAIEmbeddings` is not fully defined; you should define `SafetySettingsType`, then call `VertexAIEmbeddings.model_rebuild()`.
``` 

Even though `safety_settings` param is optional. I also tried it by adding safety_settings object but it did not work

```python
safety_settings = {
      HarmCategory.HARM_CATEGORY_UNSPECIFIED: HarmBlockThreshold.BLOCK_NONE,
      HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: HarmBlockThreshold.BLOCK_MEDIUM_AND_ABOVE,
      HarmCategory.HARM_CATEGORY_HATE_SPEECH: HarmBlockThreshold.BLOCK_ONLY_HIGH,
      HarmCategory.HARM_CATEGORY_HARASSMENT: HarmBlockThreshold.BLOCK_LOW_AND_ABOVE,
      HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: HarmBlockThreshold.BLOCK_NONE,
}
self._model = VertexAIEmbeddings(
      model_name=self._model_name,
      project=self._project_id,
      location=self._location,
      safety_settings=safety_settings,
)
```

**Comment by huzaifa50** [comment]
This is the temporary fix which worked for me

```python
# Define SafetySettingsType
class SafetySettingsType:
    # Define the necessary fields and methods
    pass

# Call model_rebuild after defining SafetySettingsType
VertexAIEmbeddings.model_rebuild()

self._model = VertexAIEmbeddings(
    model_name=self._model_name,
    project=self._project_id,
    location=self._location,
)
```

**Comment by hutariq** [comment]
This is the temporary fix which worked for me

```python
# Define SafetySettingsType
class SafetySettingsType:
    # Define the necessary fields and methods
    pass

# Call model_rebuild after defining SafetySettingsType
VertexAIEmbeddings.model_rebuild()

self._model = VertexAIEmbeddings(
    model_name=self._model_name,
    project=self._project_id,
    location=self._location,
)
```
